{
	"openapi": "3.0.1",
	"info": {
		"title": "OpenAPI definition",
		"version": "v0"
	},
	"servers": [
		{
			"url": "http://localhost:8080",
			"description": "Generated server url"
		}
	],
	"paths": {
		"/v2/api-docs": {
			"get": {
				"tags": [
					"swagger-2-controller-web-mvc"
				],
				"operationId": "getDocumentation",
				"parameters": [
					{
						"name": "group",
						"in": "query",
						"required": false,
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "string"
								}
							},
							"application/hal+json": {
								"schema": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		},
		"/v1/sales": {
			"get": {
				"tags": [
					"sale-controller"
				],
				"operationId": "findAllSales",
				"parameters": [
					{
						"name": "minDate",
						"in": "query",
						"required": false,
						"schema": {
							"type": "string",
							"default": ""
						}
					},
					{
						"name": "maxDate",
						"in": "query",
						"required": false,
						"schema": {
							"type": "string",
							"default": ""
						}
					},
					{
						"name": "pageable",
						"in": "query",
						"required": true,
						"schema": {
							"$ref": "#/components/schemas/Pageable"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"*/*": {
								"schema": {
									"$ref": "#/components/schemas/PageSale"
								}
							}
						}
					}
				}
			}
		},
		"/swagger-resources": {
			"get": {
				"tags": [
					"api-resource-controller"
				],
				"operationId": "swaggerResources",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/SwaggerResource"
									}
								}
							}
						}
					}
				}
			}
		},
		"/swagger-resources/configuration/ui": {
			"get": {
				"tags": [
					"api-resource-controller"
				],
				"operationId": "uiConfiguration",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/UiConfiguration"
								}
							}
						}
					}
				}
			}
		},
		"/swagger-resources/configuration/security": {
			"get": {
				"tags": [
					"api-resource-controller"
				],
				"operationId": "securityConfiguration",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/SecurityConfiguration"
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"Pageable": {
				"type": "object",
				"properties": {
					"page": {
						"minimum": 0,
						"type": "integer",
						"format": "int32"
					},
					"size": {
						"minimum": 1,
						"type": "integer",
						"format": "int32"
					},
					"sort": {
						"type": "array",
						"items": {
							"type": "string"
						}
					}
				}
			},
			"PageSale": {
				"type": "object",
				"properties": {
					"totalPages": {
						"type": "integer",
						"format": "int32"
					},
					"totalElements": {
						"type": "integer",
						"format": "int64"
					},
					"size": {
						"type": "integer",
						"format": "int32"
					},
					"content": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Sale"
						}
					},
					"number": {
						"type": "integer",
						"format": "int32"
					},
					"sort": {
						"$ref": "#/components/schemas/Sort"
					},
					"first": {
						"type": "boolean"
					},
					"last": {
						"type": "boolean"
					},
					"numberOfElements": {
						"type": "integer",
						"format": "int32"
					},
					"pageable": {
						"$ref": "#/components/schemas/PageableObject"
					},
					"empty": {
						"type": "boolean"
					}
				}
			},
			"PageableObject": {
				"type": "object",
				"properties": {
					"offset": {
						"type": "integer",
						"format": "int64"
					},
					"sort": {
						"$ref": "#/components/schemas/Sort"
					},
					"pageSize": {
						"type": "integer",
						"format": "int32"
					},
					"pageNumber": {
						"type": "integer",
						"format": "int32"
					},
					"paged": {
						"type": "boolean"
					},
					"unpaged": {
						"type": "boolean"
					}
				}
			},
			"Sale": {
				"type": "object",
				"properties": {
					"id": {
						"type": "integer",
						"format": "int64"
					},
					"sellerName": {
						"type": "string"
					},
					"visited": {
						"type": "integer",
						"format": "int32"
					},
					"deals": {
						"type": "integer",
						"format": "int32"
					},
					"amount": {
						"type": "number",
						"format": "double"
					},
					"date": {
						"type": "string",
						"format": "date"
					}
				}
			},
			"Sort": {
				"type": "object",
				"properties": {
					"empty": {
						"type": "boolean"
					},
					"sorted": {
						"type": "boolean"
					},
					"unsorted": {
						"type": "boolean"
					}
				}
			},
			"SwaggerResource": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"url": {
						"type": "string"
					},
					"swaggerVersion": {
						"type": "string"
					},
					"location": {
						"type": "string",
						"deprecated": true
					}
				}
			},
			"UiConfiguration": {
				"type": "object",
				"properties": {
					"deepLinking": {
						"type": "boolean"
					},
					"displayOperationId": {
						"type": "boolean"
					},
					"defaultModelsExpandDepth": {
						"type": "integer",
						"format": "int32"
					},
					"defaultModelExpandDepth": {
						"type": "integer",
						"format": "int32"
					},
					"defaultModelRendering": {
						"type": "string",
						"enum": [
							"example",
							"model"
						]
					},
					"displayRequestDuration": {
						"type": "boolean"
					},
					"docExpansion": {
						"type": "string",
						"enum": [
							"none",
							"list",
							"full"
						]
					},
					"filter": {
						"type": "object"
					},
					"maxDisplayedTags": {
						"type": "integer",
						"format": "int32"
					},
					"operationsSorter": {
						"type": "string",
						"enum": [
							"alpha",
							"method"
						]
					},
					"showExtensions": {
						"type": "boolean"
					},
					"showCommonExtensions": {
						"type": "boolean"
					},
					"tagsSorter": {
						"type": "string",
						"enum": [
							"alpha"
						]
					},
					"validatorUrl": {
						"type": "string"
					},
					"supportedSubmitMethods": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"swaggerBaseUiUrl": {
						"type": "string"
					}
				}
			},
			"SecurityConfiguration": {
				"type": "object",
				"properties": {
					"apiKey": {
						"type": "string",
						"deprecated": true
					},
					"apiKeyVehicle": {
						"type": "string",
						"deprecated": true
					},
					"apiKeyName": {
						"type": "string",
						"deprecated": true
					},
					"clientId": {
						"type": "string"
					},
					"clientSecret": {
						"type": "string"
					},
					"realm": {
						"type": "string"
					},
					"appName": {
						"type": "string"
					},
					"scopeSeparator": {
						"type": "string"
					},
					"additionalQueryStringParams": {
						"type": "object",
						"additionalProperties": {
							"type": "object"
						}
					},
					"useBasicAuthenticationWithAccessCodeGrant": {
						"type": "boolean"
					},
					"enableCsrfSupport": {
						"type": "boolean"
					}
				}
			}
		}
	}
}
